create table public.page_views (
  id bigint generated by default as identity,
  page text not null,
  views bigint null default '1'::bigint,
  last_update timestamp without time zone not null default now(),
  constraint page_views_pkey primary key (id),
  constraint page_views_page_key unique (page)
) tablespace pg_default;

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.increment_views(page_slug text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    IF EXISTS (SELECT FROM page_views WHERE page=page_slug) THEN
        UPDATE page_views
        SET views = views + 1,
            last_update = now()
        WHERE page = page_slug;
    ELSE
        INSERT into page_views(page) VALUES (page_slug);
    END IF;
END;$function$
;