create table public.favorites (
  id bigint generated by default as identity,
  user_id uuid not null,
  product_id bigint not null,
  constraint favorites_pkey primary key (id),
  constraint favorites_id_key unique (id),
  constraint favorites_product_id_fkey foreign key (product_id) references products (id)
) tablespace pg_default;